"""
An extensible genomic database based on file objects and featuring a fixed interaction interface.

The implementation is very straightforward:
1. Assign a UUID to each file and folder; if necessary, compress sequence files into .bgz format, convert GFF files to
   Parquet databases, or generate CDS and PEP sequences based on the specified codon type
2. Use a single-node database to store the metadata. The metadata may include the corresponding species name, phylogenetic
   tree, MD5 hash, and genome overview
3. Define a set of interactive interfaces
"""

import json
import os
from pathlib import Path
from typing import List, Optional, Literal
from dataclasses import dataclass
import shutil

from genevue import console, DirNotExistsError, DirNotEmptyError
from genevue.Remote.NCBI_DATASETS_API import Datasets4Genome


@dataclass
class GenomeDatabaseMetadataLineage:
    order: str
    family: str
    genus: str
    species: str
    common_name: str


@dataclass
class GenomeDatabaseMetadataAsmInfo:
    name: str
    level: str
    type: str
    atgccount: int
    gccount: int
    size: int
    ungappedsize: int
    contig_count: int
    contig_l50: int
    contig_n50: int
    scaffold_count: int
    scaffold_l50: int
    scaffold_n50: int
    chromosome_count: int
    organelles_count: int


@dataclass
class BUSCOResult:
    total: int
    complete: int
    complete_ratio: float
    singlecopy: int
    singlecopy_ratio: float
    duplicated: int
    duplicated_ratio: float
    fragmented: int
    fragmented_ratio: float
    missing: int
    missing_ratio: float


@dataclass
class GenomeDatabaseMetadataAnnoInfo:
    name: str
    genes_total_count: int
    genes_protein_coding: int
    genes_non_coding: int
    genes_pseudogene: int
    genes_other: int
    busco_lineage: str
    busco_version: str
    busco_result: BUSCOResult


@dataclass
class GenomeDatabaseMetadata:
    source: str
    accession: str
    lineage: GenomeDatabaseMetadataLineage
    asminfo: GenomeDatabaseMetadataAsmInfo
    annoinfo: GenomeDatabaseMetadataAnnoInfo


class GenomeDatabase:
    def __init__(
        self,
        dbdir: Path,
        seq2bgz: bool = False,
        gff2parquet: bool = False,
        autogen_cds_and_pep: bool = False,
        internet_connection: bool = False,
        force_to_create_dir: bool = False,
        force_to_rebuild_db: bool = False,
    ):
        self.dbdir = dbdir
        self.seq2bgz = seq2bgz
        self.gff2parquet = gff2parquet
        self.autogen_cds_and_pep = autogen_cds_and_pep
        self.internet_connection = internet_connection
        self.force_to_create_dir = force_to_create_dir
        self.force_to_rebuild_db = force_to_rebuild_db

    def create(self):
        if not self.force_to_create_dir and not self.dbdir.exists():
            console.exception(DirNotExistsError)

        if self.force_to_create_dir:
            dbdir_parent_list: list[Path] = list(self.dbdir.parents)
            dbdir_parent_list.reverse()
            dbdir_parent_list.append(self.dbdir)
            for parent_dir in dbdir_parent_list:
                parent_dir.mkdir(exist_ok=True)

        if list(self.dbdir.glob("**/*")):
            if "" in list(self.dbdir.glob("**/*")):
                console.exception()
            elif not self.force_to_rebuild_db:
                console.exception(DirNotEmptyError)
            else:
                # delete all data
                shutil.rmtree(self.dbdir)
                os.mkdir(self.dbdir)

        # create start
        # inject metadata
        default_metadata = {
            "dbver": 0,
            "dbpath": str(self.dbdir),
            "flags": {
                "seq2bgz": self.seq2bgz,
                "gff2parquet": self.gff2parquet,
                "autogen_cds_and_pep": self.autogen_cds_and_pep,
                "internet_connection": self.internet_connection,
                "force_to_rebuild_db": self.force_to_rebuild_db,
            },
            "genomes": [],
        }
        json.dump(default_metadata, open(self.dbdir / "dbmetadata.json", "w"))
        with open(self.dbdir / "DO_NOT_EDIT_MANUALLY", "w") as f:
            f.write(
                "This dir was generated by genome database module of GeneVue.\n"
                "DO NOT EDIT MANUALLY.\n"
            )

    def read(self):
        pass

    def extend_local(
        self,
        species_name: str,
        asm_report: Optional[Path] = None,
        gff3: Optional[Path] = None,
        gtf: Optional[Path] = None,
        genome_seq: Optional[Path] = None,
        rna: Optional[Path] = None,
        pep: Optional[Path] = None,
        gbff: Optional[Path] = None,
        metadata: Optional[Path] = None,
        metadata_type: Literal["NCBI"] = "NCBI",
    ):
        pass

    def extend_remote(
        self,
        accession_list: list,
        include,
        keep_zip: bool = True,
        chunk_size: int = 20,
    ):
        d4g = Datasets4Genome(
            accessions=accession_list,
            target_dir=self.dbdir,
            include=include,
            chunk_size=chunk_size,
            generate_symlinks=True,
        )
        d4g.download()

        # get_meta_data
        pass

    def remove(
        self,
        species_name: str,
        entries: Optional[
            List[
                Literal["asm_report", "gff3", "gtf", "genome_seq", "rna", "pep", "gbff"]
            ]
        ] = None,
    ):
        pass

    def generate_cds_pep(self, species_name: str):
        pass

    def show_species(self):
        pass

    def show_metadata(self):
        pass
