name: Package Build and Publish (PyPI)

on:
  push:
    tags:
    - 'v*'
  release:
    types: [published]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Build
        run: uv build

      - name: Publish package to PyPI
        run: uv publish --tokens ${{ secrets.PYPI_API_TOKEN }}
